title: Karigiri.net Family Blog
description: >
  This blog is for Karigiri.net family members to share their thoughts
  on all things relevant to the family. If you are one of us, please do contribute.
  We welcome posts in Kannada/English.
copyright: None
sass:
  sass_dir: assets/sass
#url: http://localhost:4000
sitehome: "http://karigiri.net"
bloghome: "http://blog.karigiri.net"
disqus_shortname: karigiri
facebook_username: "groups/karigiri.net/"
#twitter_username: "#"
#linkedin_username: "#"
#instagram_username:
#pinterest_username:
#flickr_username:
#github_username:  "#"
feed_icon: rss
email: "hello@karigiri.net"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
